"""Professional A4 (landscape) PDF report for an engineering prediction."""
import io
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4, landscape
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (Paragraph, SimpleDocTemplate, Spacer, Table,
                                TableStyle)

BLUE = colors.HexColor("#1f4e79")
LIGHT = colors.HexColor("#eef3f8")
GOLD = colors.HexColor("#fff3cd")


def _footer(canvas, doc):
    canvas.saveState()
    canvas.setFont("Helvetica", 7.5)
    canvas.setFillColor(colors.grey)
    ts = datetime.now().strftime("%d %b %Y, %I:%M %p")
    canvas.drawString(14 * mm, 8 * mm,
                      f"Generated by Engineering College Predictor  |  {ts}")
    canvas.drawRightString(283 * mm, 8 * mm, f"Page {doc.page}")
    canvas.restoreState()


def _join(items, label):
    if not items:
        return f"All {label}"
    txt = ", ".join(items[:8])
    return txt + (f" (+{len(items) - 8} more)" if len(items) > 8 else "")


def build_prediction_pdf(pred: dict) -> bytes:
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=landscape(A4), leftMargin=12 * mm,
                            rightMargin=12 * mm, topMargin=12 * mm,
                            bottomMargin=16 * mm)
    styles = getSampleStyleSheet()
    cell = ParagraphStyle("cell", parent=styles["Normal"], fontSize=8, leading=10)
    head = ParagraphStyle("head", parent=styles["Normal"], fontSize=8.5,
                          leading=10, textColor=colors.white,
                          fontName="Helvetica-Bold")
    lbl = ParagraphStyle("lbl", parent=styles["Normal"], fontSize=9,
                         fontName="Helvetica-Bold", textColor=BLUE)
    val = ParagraphStyle("val", parent=styles["Normal"], fontSize=9)

    show_cat = pred.get("show_category", True)
    input_label = "Percentile" if pred["mode"] == "percentile" else "Rank"
    input_value = (f"{pred['value']:g}" if pred["mode"] == "percentile"
                   else f"{int(pred['value']):,}")

    details = Table([
        [Paragraph("Student Name", lbl),
         Paragraph(pred.get("student_name") or "-", val),
         Paragraph("Exam", lbl), Paragraph(pred.get("exam", "-"), val),
         Paragraph(input_label, lbl), Paragraph(input_value, val)],
        [Paragraph("Category", lbl),
         Paragraph((pred.get("category") or "-") if show_cat else "N/A", val),
         Paragraph("Branches", lbl),
         Paragraph(_join(pred.get("branches"), "Branches"), val),
         Paragraph("Options", lbl), Paragraph(str(pred["count"]), val)],
        [Paragraph("Districts", lbl),
         Paragraph(_join(pred.get("districts"), "Districts"), val),
         Paragraph("Date", lbl),
         Paragraph(datetime.now().strftime("%d %b %Y, %I:%M %p"), val),
         Paragraph("", lbl), Paragraph("", val)],
    ], colWidths=[24 * mm, 60 * mm, 20 * mm, 74 * mm, 22 * mm, 40 * mm])
    details.setStyle(TableStyle([
        ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#c9d6e5")),
        ("BACKGROUND", (0, 0), (0, -1), LIGHT),
        ("BACKGROUND", (2, 0), (2, -1), LIGHT),
        ("BACKGROUND", (4, 0), (4, -1), LIGHT),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
    ]))

    story = [
        Paragraph("Engineering College Predictor", styles["Title"]),
        Spacer(1, 2 * mm),
        Paragraph("MH-CET &amp; JEE-Main - Prediction Report",
                  ParagraphStyle("sub", parent=styles["Normal"], alignment=1,
                                 fontSize=11, textColor=colors.grey)),
        Spacer(1, 4 * mm), details, Spacer(1, 6 * mm)]

    headers = ["Sr.No", "College Code", "College Name", "District", "Branch",
               "Category", "Status", "Cutoff Percentile", "Cutoff Rank"]
    data = [[Paragraph(h, head) for h in headers]]
    pri_rows = []
    for idx, r in enumerate(pred["results"], start=1):
        name = r["college_name"]
        if r.get("priority"):
            name = "\u2605 " + name
            pri_rows.append(idx)
        data.append([
            Paragraph(str(r["sr_no"]), cell),
            Paragraph(str(r["college_code"]), cell),
            Paragraph(name, cell),
            Paragraph(r.get("district", "-"), cell),
            Paragraph(r["branch"], cell),
            Paragraph(r.get("category", "-"), cell),
            Paragraph(r.get("status", "-"), cell),
            Paragraph(f'{r["cutoff_percentile"]:.4f}'
                      if r["cutoff_percentile"] is not None else "-", cell),
            Paragraph(f'{r["cutoff_rank"]:,}'
                      if r["cutoff_rank"] is not None else "-", cell)])
    table = Table(data, colWidths=[11 * mm, 18 * mm, 62 * mm, 20 * mm, 48 * mm,
                                   20 * mm, 22 * mm, 24 * mm, 18 * mm],
                  repeatRows=1)
    tstyle = [
        ("BACKGROUND", (0, 0), (-1, 0), BLUE),
        ("GRID", (0, 0), (-1, -1), 0.4, colors.grey),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, LIGHT]),
    ]
    for ri in pri_rows:
        tstyle.append(("BACKGROUND", (0, ri), (-1, ri), GOLD))
    table.setStyle(TableStyle(tstyle))
    story.append(table)
    doc.build(story, onFirstPage=_footer, onLaterPages=_footer)
    return buf.getvalue()
