"""Professional A4 (landscape) PDF report for an engineering prediction."""
import io
import os
from datetime import datetime


from reportlab.lib import colors
from reportlab.lib.pagesizes import A4, landscape
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (Paragraph, SimpleDocTemplate, Spacer, Table,
                                TableStyle)

BLUE = colors.HexColor("#1f4e79")
LIGHT = colors.HexColor("#eef3f8")


_ASSETS = os.path.join(os.path.dirname(__file__), "..", "assets")

# Per-account PDF branding: header logo (top of every page), watermark
# (behind the content), and a custom footer line.
PARTNER_BRANDING = {
    "gncnanded@gmail.com": {
        "header_image": os.path.join(_ASSETS, "grovy_header.png"),
        "watermark_image": os.path.join(_ASSETS, "grovy_watermark.png"),
        "footer": ("Patil Complex Bhagya Nagar T Point Nanded "
                   "9921770747/8379069919"),
    },
}


def get_branding(email: str | None) -> dict | None:
    return PARTNER_BRANDING.get((email or "").strip().lower())


def _page_decorator(branding: dict | None = None):
    """Draws (per page, under the content): watermark, header logo, footer."""
    def draw(canvas, doc):
        canvas.saveState()
        page_w, page_h = landscape(A4)
        if branding:
            wm = branding.get("watermark_image")
            if wm and os.path.exists(wm):
                side = 130 * mm
                canvas.drawImage(wm, (page_w - side) / 2,
                                 (page_h - side) / 2, side, side,
                                 preserveAspectRatio=True, mask="auto")
            hd = branding.get("header_image")
            if hd and os.path.exists(hd):
                box_w, box_h = 180 * mm, 46 * mm
                canvas.drawImage(hd, (page_w - box_w) / 2,
                                 page_h - box_h - 4 * mm,
                                 box_w, box_h,
                                 preserveAspectRatio=True,
                                 anchor="c", mask="auto")
        ts = datetime.now().strftime("%d %b %Y, %I:%M %p")
        if branding:
            canvas.setFont("Helvetica-Bold", 8.5)
            canvas.setFillColor(colors.HexColor("#333333"))
            canvas.drawCentredString(page_w / 2, 8 * mm, branding["footer"])
            canvas.setFont("Helvetica", 7)
            canvas.setFillColor(colors.grey)
            canvas.drawRightString(page_w - 12 * mm, 8 * mm,
                                   f"Page {doc.page}")
        else:
            canvas.setFont("Helvetica", 7.5)
            canvas.setFillColor(colors.grey)
            canvas.drawString(14 * mm, 8 * mm,
                              "Generated by Engineering College Predictor"
                              f"  |  {ts}")
            canvas.drawRightString(283 * mm, 8 * mm, f"Page {doc.page}")
        canvas.restoreState()
    return draw


def _university(row: dict) -> str:
    """Short Home / Other-than-Home label for the University column."""
    ht = (row.get("home_type") or "-").strip()
    if ht == "Home University":
        return "Home University"
    if ht == "Other than Home University":
        return "Other than Home"
    return "-"


def build_prediction_pdf(pred: dict, branding: dict | None = None) -> bytes:
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=landscape(A4), leftMargin=12 * mm,
                            rightMargin=12 * mm,
                            topMargin=(56 * mm if branding else 12 * mm),
                            bottomMargin=16 * mm)
    styles = getSampleStyleSheet()
    cell = ParagraphStyle("cell", parent=styles["Normal"], fontSize=8,
                          leading=10)
    head = ParagraphStyle("head", parent=styles["Normal"], fontSize=8.5,
                          leading=10, textColor=colors.white,
                          fontName="Helvetica-Bold")
    lbl = ParagraphStyle("lbl", parent=styles["Normal"], fontSize=9,
                         fontName="Helvetica-Bold", textColor=BLUE)
    val = ParagraphStyle("val", parent=styles["Normal"], fontSize=9)

    show_cat = pred.get("show_category", True)
    is_pct = pred["mode"] == "percentile"
    input_label = "Percentile" if is_pct else "Rank"
    input_value = (f"{pred['value']:g}" if is_pct
                   else f"{int(pred['value']):,}")

    # ---- header details: Student Name | Percentile or Rank | Category ------
    rows = [[
        Paragraph("Student Name", lbl),
        Paragraph(pred.get("student_name") or "-", val),
        Paragraph(input_label, lbl),
        Paragraph(input_value, val),
        Paragraph("Category", lbl),
        Paragraph((pred.get("category") or "-") if show_cat else "N/A", val),
    ]]
    home_univ = pred.get("home_university") or ""
    if home_univ:
        rows.append([
            Paragraph("Home University", lbl),
            Paragraph(home_univ, val),
            Paragraph("Total", lbl),
            Paragraph(str(pred["count"]), val),
            Paragraph("Date", lbl),
            Paragraph(datetime.now().strftime("%d %b %Y"), val),
        ])

    details = Table(rows, colWidths=[30 * mm, 78 * mm, 24 * mm, 45 * mm,
                                     24 * mm, 66 * mm])
    details.setStyle(TableStyle([
        ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#c9d6e5")),
        ("BACKGROUND", (0, 0), (0, -1), LIGHT),
        ("BACKGROUND", (2, 0), (2, -1), LIGHT),
        ("BACKGROUND", (4, 0), (4, -1), LIGHT),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
    ]))

    story = [
        Paragraph("Engineering College Predictor", styles["Title"]),
        Spacer(1, 4 * mm), details, Spacer(1, 6 * mm)]

    # ---- results table ----------------------------------------------------
    headers = ["Sr.No", "College Code", "College Name", "District", "Branch",
               "University", "Percentile", "Merit Rank"]
    data = [[Paragraph(h, head) for h in headers]]
    for r in pred["results"]:
        name = r["college_name"]
        if r.get("priority"):
            name = "\u2605 " + name
        data.append([
            Paragraph(str(r["sr_no"]), cell),
            Paragraph(str(r["college_code"]), cell),
            Paragraph(name, cell),
            Paragraph(r.get("district", "-"), cell),
            Paragraph(r["branch"], cell),
            Paragraph(_university(r), cell),
            Paragraph(f'{r["cutoff_percentile"]:.4f}'
                      if r["cutoff_percentile"] is not None else "-", cell),
            Paragraph(f'{r["cutoff_rank"]:,}'
                      if r["cutoff_rank"] is not None else "-", cell)])

    table = Table(data, colWidths=[12 * mm, 20 * mm, 76 * mm, 24 * mm,
                                   58 * mm, 32 * mm, 24 * mm, 21 * mm],
                  repeatRows=1)
    tstyle = [
        ("BACKGROUND", (0, 0), (-1, 0), BLUE),
        ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#9aa7b4")),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        # standard alignment: numbers centred / right, text left
        ("ALIGN", (0, 0), (1, -1), "CENTER"),      # Sr.No, College Code
        ("ALIGN", (5, 0), (5, -1), "CENTER"),      # University
        ("ALIGN", (6, 0), (7, -1), "RIGHT"),       # Percentile, Merit Rank
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("LEFTPADDING", (0, 0), (-1, -1), 4),
        ("RIGHTPADDING", (0, 0), (-1, -1), 4),
    ]
    table.setStyle(TableStyle(tstyle))
    story.append(table)
    deco = _page_decorator(branding)
    doc.build(story, onFirstPage=deco, onLaterPages=deco)
    return buf.getvalue()


def build_college_list_pdf(data: dict,
                           branding: dict | None = None) -> bytes:
    """College List report: same standard styling as the prediction PDF,
    plus a Category column (the list can mix categories)."""
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=landscape(A4), leftMargin=12 * mm,
                            rightMargin=12 * mm,
                            topMargin=(56 * mm if branding else 12 * mm),
                            bottomMargin=16 * mm)
    styles = getSampleStyleSheet()
    cell = ParagraphStyle("cell", parent=styles["Normal"], fontSize=8,
                          leading=10)
    head = ParagraphStyle("head", parent=styles["Normal"], fontSize=8.5,
                          leading=10, textColor=colors.white,
                          fontName="Helvetica-Bold")
    lbl = ParagraphStyle("lbl", parent=styles["Normal"], fontSize=9,
                         fontName="Helvetica-Bold", textColor=BLUE)
    val = ParagraphStyle("val", parent=styles["Normal"], fontSize=9)

    gender_label = {"gender-neutral": "Gender-Neutral",
                    "ladies": "Female (Ladies)",
                    "any": "Any"}.get((data.get("gender") or "").lower(),
                                      "Gender-Neutral")

    rows = [[
        Paragraph("Category", lbl),
        Paragraph(data.get("category") or "All", val),
        Paragraph("Gender / Seat Type", lbl),
        Paragraph(gender_label, val),
        Paragraph("Total Colleges", lbl),
        Paragraph(str(data.get("count", 0)), val),
    ], [
        Paragraph("Home University", lbl),
        Paragraph(data.get("home_university") or "-", val),
        Paragraph("12th Pass District", lbl),
        Paragraph(data.get("home_district") or "-", val),
        Paragraph("Date", lbl),
        Paragraph(datetime.now().strftime("%d %b %Y"), val),
    ]]
    details = Table(rows, colWidths=[30 * mm, 78 * mm, 34 * mm, 35 * mm,
                                     28 * mm, 62 * mm])
    details.setStyle(TableStyle([
        ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#c9d6e5")),
        ("BACKGROUND", (0, 0), (0, -1), LIGHT),
        ("BACKGROUND", (2, 0), (2, -1), LIGHT),
        ("BACKGROUND", (4, 0), (4, -1), LIGHT),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
    ]))

    story = [Paragraph("MH-CET College List", styles["Title"]),
             Spacer(1, 4 * mm), details, Spacer(1, 6 * mm)]

    headers = ["Sr.No", "College Code", "College Name", "District", "Branch",
               "Category", "University", "Percentile", "Merit Rank"]
    data_rows = [[Paragraph(h, head) for h in headers]]
    for r in data.get("results", []):
        data_rows.append([
            Paragraph(str(r["sr_no"]), cell),
            Paragraph(str(r["college_code"]), cell),
            Paragraph(r["college_name"], cell),
            Paragraph(r.get("district", "-"), cell),
            Paragraph(r["branch"], cell),
            Paragraph(r.get("category", "-"), cell),
            Paragraph(_university(r), cell),
            Paragraph(f'{r["cutoff_percentile"]:.4f}'
                      if r["cutoff_percentile"] is not None else "-", cell),
            Paragraph(f'{r["cutoff_rank"]:,}'
                      if r["cutoff_rank"] is not None else "-", cell)])

    table = Table(data_rows, colWidths=[12 * mm, 18 * mm, 64 * mm, 24 * mm,
                                        52 * mm, 20 * mm, 30 * mm, 24 * mm,
                                        21 * mm], repeatRows=1)
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), BLUE),
        ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#9aa7b4")),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("ALIGN", (0, 0), (1, -1), "CENTER"),
        ("ALIGN", (5, 0), (6, -1), "CENTER"),
        ("ALIGN", (7, 0), (8, -1), "RIGHT"),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("LEFTPADDING", (0, 0), (-1, -1), 4),
        ("RIGHTPADDING", (0, 0), (-1, -1), 4),
    ]))
    story.append(table)
    deco = _page_decorator(branding)
    doc.build(story, onFirstPage=deco, onLaterPages=deco)
    return buf.getvalue()
